Max dev
coyjiv/Rombo pull request #12
Opened 2023-10-03 15:11 UTC by 1Maxuta1

Skeleton people + refactoring

2023-10-04 21:34 UTC, 1Maxuta1 reviewed
nice

2023-10-04 21:52 UTC, coyjiv commented on public/img/avatar.jpg
у тебя уже был этот файл

2023-10-04 21:52 UTC, coyjiv commented on package.json
> +    "@cloudinary/react": "^1.11.2",
не нужно, так как не относиться к коммиту

2023-10-04 21:53 UTC, coyjiv commented on package.json
> +    "@cloudinary/url-gen": "^1.11.2",
тоже самое

2023-10-04 21:53 UTC, coyjiv commented on package.json
> +    "cloudinary": "^1.41.0",
тоже самое #2

2023-10-04 21:53 UTC, coyjiv commented on package.json
> +    "cloudinary-react": "^1.8.1",
#3

2023-10-04 21:54 UTC, coyjiv commented on package.json
> +    "cloudinary": "^1.41.0",
на ссылки забей

2023-10-04 21:54 UTC, coyjiv commented on package.json
> +    "next-cloudinary": "^4.22.0",
тоже убери

2023-10-04 21:54 UTC, coyjiv commented on next.config.js
> +
не включай файлы где из изменений - форматирование в коммит

2023-10-04 21:55 UTC, coyjiv commented on public/img/avatar.jpg
удали...

2023-10-04 21:55 UTC, coyjiv commented on public/img/avatar.webp
и этот был

2023-10-04 21:56 UTC, coyjiv commented on src/app/actions/users/index.ts
вынеси в редакс, сделай новый слайс под юзеров

2023-10-04 21:57 UTC, coyjiv commented on src/components/buttons.tsx
Супер, перенеси сюда также другие кнопки которые ты создавал из папки /buttons а её - удали

2023-10-04 21:59 UTC, coyjiv commented on src/components/views/EditProfile/index.tsx
Сделай интерфейс и выноси типы. Any - это как временный фикс какой-то проблемы но это по сути лишение преимуществ типизации

2023-10-04 22:00 UTC, coyjiv commented on src/components/views/EditProfile/index.tsx
> +    notifySuccess();
наверное лучше поднять notifySuccess в блок try, так получается у тебя в любом случае вылетит notifySuccess, не?

2023-10-04 22:01 UTC, coyjiv commented on src/pages/friends/index.tsx
> +const Friends = ({}: any) => {
если пропсов нет то зачем {}:any?)

2023-10-04 22:04 UTC, coyjiv requested changes
В целом хорошо, но есть что исправить

2023-10-18 21:28 UTC, coyjiv commented
Ещё конфликты пофикси, спулься с мейна и всё должно быть супер (в профиле ещё мб пару проблем но там изи)

2023-10-19 14:24 UTC, closed without merging